#!/usr/bin/env python3
"""Make arcade_data.lua and the path blob from psp/arcade_data.h (which tools/gen_arcade.py makes): the numbers of the arcade rules.
They come from tomcoolpxl/cool8-cpu (MIT), a Python model of the arcade program (see ../ARCADE.md).

The cart has little room for code (15.6 KB compressed), and the 62 flight paths (19,000 steps) do not fit in it. So:
  - the steps of the paths are a bit stream in free memory of the cart: the map (0x2000..0x2fff) and the sprite sheet rows 24..63
    (0x0600..0x0fff). For each path: the change from step to step of dx (the first value from 0), then of dy.
    Code of a value: 0 -> 0, 1 -> 10, -1 -> 110, 2 -> 1110, -2 -> 11110, else 11111 and 9 bits (value + 256).
    The bits are read from the low bit of a byte. 5 KB in all. gen_assets.py puts the blob in galaga.p8; tests/trace.p8 is made here.
  - everything else is in strings in arcade_data.lua. A list of integers is a string of base-36 characters (0-9 a-y: -8..26; no
    capitals: the editor changes them; z + 2 characters: a long number, +500). game.lua decodes them (dec).
Usage: python3 tools/gen_arcade_p8.py"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
H = open(os.path.join(ROOT, '..', 'psp', 'arcade_data.h')).read()
DIG = '0123456789abcdefghijklmnopqrstuvwxyz'
MAP_BYTES = 4096                    # the blob: map memory first, then the sprite sheet from row 24
GFX_ROW0, GFX_BYTES = 24, 40 * 64
CODE = {0: '0', 1: '10', -1: '110', 2: '1110', -2: '11110'}


def enc(xs):
    out = ''
    for x in xs:
        if -8 <= x <= 26:
            out += DIG[x + 8]
        else:
            assert -500 <= x < 796, x
            out += 'z' + DIG[(x + 500) // 36] + DIG[(x + 500) % 36]
    return out


def nums(text):
    return [int(v) for v in re.findall(r'-?\d+', text)]


def block(name):
    m = re.search(r'\b' + name + r'(?:\[[^\]]*\])+\s*=\s*\{(.*?)\n?\};', H, re.S)
    return m.group(1)


def arr(prefix, n):
    return [nums(re.search(r'\b%s%d\[\](?:\[3\])?\s*=\s*\{(.*?)\};' % (prefix, i), H, re.S).group(1)) for i in range(n)]


paths = arr('arc_p', 48)
pmeta = [nums(l)[:4] for l in block('arc_path').strip().split('\n')]            # sx, sy, n, bt
dives = arr('arc_d', 14)
dmeta = [nums(l)[:2] for l in block('arc_dive_path').strip().split('\n')]       # n, total
assert [len(p) // 2 for p in paths] == [m[2] for m in pmeta] and [len(d) // 2 for d in dives] == [m[0] for m in dmeta]


def blob():
    bits = ''
    for p in paths + dives:
        for stream in (p[0::2], p[1::2]):
            prev = 0
            for v in stream:
                d, prev = v - prev, v
                bits += CODE.get(d) or '11111' + ''.join(str((d + 256) >> i & 1) for i in range(9))
    bits += '0' * (-len(bits) % 8)
    out = bytearray(int(bits[i:i + 8][::-1], 2) for i in range(0, len(bits), 8))      # the first bit is the low bit
    assert len(out) <= MAP_BYTES + GFX_BYTES, len(out)
    return out


def place(px, b):
    """Put the part of the blob that lives in the sprite sheet into px (128 rows of 128 pixels of 4 bits)."""
    for k, v in enumerate(b[MAP_BYTES:]):
        row, x = GFX_ROW0 + k // 64, (k % 64) * 2
        px[row][x], px[row][x + 1] = v & 15, v >> 4


def map_section(b):
    m = bytes(b[:MAP_BYTES]).ljust(MAP_BYTES, b'\0')
    return '__map__\n' + '\n'.join(''.join('%02x' % v for v in m[r * 128:(r + 1) * 128]) for r in range(32)) + '\n'


def main():
    lines = ['-- generated by tools/gen_arcade_p8.py from psp/arcade_data.h: do not edit',
             '-- numbers of the arcade rules (see ARCADE.md), from tomcoolpxl/cool8-cpu (MIT), a model of the arcade program',
             '-- a string is a list of integers: 0-9 a-y = -8..26, z + 2 characters = a long number (+500); game.lua: dec()',
             '-- the steps of the paths are in the map memory and in the sprite sheet rows 24..63 (see tools/gen_arcade_p8.py)', '',
             '-- entry paths: start x, start y, frames to the first bomb, number of steps', 'a_path={']
    for (sx, sy, n, bt) in pmeta:
        lines.append('"%s",' % enc([sx, sy, bt, n]))
    lines += ['}', '-- dive paths: frames of the whole dive, number of steps', 'a_dive={']
    for (n, total) in dmeta:
        lines.append('"%s",' % enc([total, n]))
    lines += ['}']
    lines.append('-- x y of the 40 slots\na_slot="%s"' % enc(nums(block('arc_slot'))))
    rows = re.findall(r'\{(\d+), (\d+), arc_w(\d+), (\d+), (\d+)\}', block('arc_row'))
    rmeta, wl = [], []
    for ch, n, w, h0, h1 in rows:
        rmeta += [int(ch), int(h0), int(h1)]
        t = nums(re.search(r'\barc_w%s\[\]\[3\]\s*=\s*\{(.*?)\};' % w, H, re.S).group(1))
        assert len(t) == 3 * int(n)
        prev, d = 0, []
        for k in range(0, len(t), 3):
            d += [t[k] - prev, t[k + 1], t[k + 2]]
            prev = t[k]
        wl.append(enc(d))
    lines.append('-- per stage row: challenge, frames between two bombs, bomb flags of a flyer; then its launches (ticks since the last launch, slot, path)')
    lines.append('a_rowhdr="%s"' % enc(rmeta))
    lines.append('a_wave={' + ',\n'.join('"%s"' % w for w in wl) + '}')
    st = nums(block('arc_stage'))
    assert len(st) == 26 * 12
    lines.append('-- per stage: its row, then the parameters p0..p10\na_stage="%s"' % enc(st))
    lines.append('a_dmap="%s"   -- [label][row][side]: dive path or -1' % enc(nums(block('arc_dive'))))
    for name, src in (('slotrow', 'arc_slot_row'), ('slotside', 'arc_slot_side'), ('slotcol', 'arc_slot_col'), ('ebomb', 'arc_entry_bomb'),
                      ('wing', 'arc_wingmen'), ('red', 'arc_red_reload'), ('bee', 'arc_bee_reload'), ('bomb', 'arc_bomb_tab')):
        lines.append('a_%s="%s"' % (name, enc(nums(block(src)))))
    b = nums(block('arc_breath'))
    assert len(b) == 640
    d = [b[k] - (b[k - 10] if k >= 10 else 0) for k in range(640)]     # the change since the step before
    lines.append('-- breathing: 64 steps of 10 numbers (5 columns, 5 rows), each is the change since the step before\na_breath="%s"' % enc(d))
    out = '\n'.join(lines) + '\n'
    open(os.path.join(ROOT, 'arcade_data.lua'), 'w').write(out)
    bl = blob()
    print('arcade_data.lua', len(out), 'bytes; blob', len(bl), 'bytes of', MAP_BYTES + GFX_BYTES)
    # tests/trace.p8: the test cart (its code is tests/trace.lua) with the same blob
    px = [[0] * 128 for _ in range(128)]
    place(px, bl)
    last = max(r for r in range(128) if any(px[r]))
    cart = ('pico-8 cartridge // http://www.pico-8.com\nversion 42\n__lua__\n-- made by tools/gen_arcade_p8.py: the code is trace.lua\n'
            '#include ../arcade_data.lua\n#include ../game.lua\n#include trace.lua\n__gfx__\n' + '\n'.join(''.join('%x' % v for v in px[r]) for r in range(last + 1)) + '\n' + map_section(bl))
    open(os.path.join(ROOT, 'tests', 'trace.p8'), 'w').write(cart)


if __name__ == '__main__':
    main()
