#!/usr/bin/env python3
"""Make paths.lua from thumby/Galaga/paths_data.py (which tools/gen_paths.py there builds from psp/game.c).
Every step delta (-3..3) is one digit (delta + 3), so a path is a short string: the cart has few tokens to spend.
Usage: python3 tools/gen_paths.py"""
import os
import sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, os.path.join(root, '..', 'thumby', 'Galaga'))
from paths_data import PATHS  # noqa: E402

rows = []
for sx, sy, n, dx, dy in PATHS:
    s = lambda d: ''.join(str(v + 3) for v in d)
    assert len(dx) == len(dy) == n and all(-3 <= v <= 3 for v in dx + dy)
    rows.append('{%d,%d,%d,"%s","%s"}' % (sx, sy, n, s(dx), s(dy)))
out = '-- generated by tools/gen_paths.py: do not edit\n-- per path: start x, start y, steps, dx digits, dy digits (digit = delta + 3)\npaths={\n' + ',\n'.join(rows) + '}\n'
open(os.path.join(root, 'paths.lua'), 'w').write(out)
print('paths.lua', len(out), 'bytes')
