#!/usr/bin/env python3
"""Make src/arcade_data.asm from ../psp/arcade_data.h: the numbers of the arcade's dive scheduler for the C64. They come from
tomcoolpxl/cool8-cpu (MIT), a model of the arcade program, through tools/gen_arcade.py of the repository (see ../ARCADE.md).
Only the tables of the rules (psp/game.c, RULES_ARCADE32) are made: the stage table columns the scheduler reads, the beam step
of each stage, and the reload tables. The C64 keeps its own flight paths and layout.
Usage: python3 tools/gen_arcade.py"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
H = open(os.path.join(ROOT, '..', 'psp', 'arcade_data.h')).read()


def block(name):
    return re.search(r'\b' + name + r'(?:\[[^\]]*\])*\s*=\s*\{(.*?)\n?\};', H, re.S).group(1)


def nums(text):
    return [int(v) for v in re.findall(r'-?\d+', text)]


stage = [nums(l) for l in block('arc_stage').strip().split('\n')]
assert len(stage) == int(re.search(r'#define ARC_NSTAGE (\d+)', H).group(1)) == 26


def lines(name, comment, items, per=16):
    out = [f'{name}: ; {comment}']
    for i in range(0, len(items), per):
        out.append('    !byte ' + ','.join(str(v & 255) for v in items[i:i + per]))
    return out + ['']


out = ['; The numbers of the arcade rules for the C64. Generated by tools/gen_arcade.py from ../psp/arcade_data.h: do not edit.',
       '; One entry for each of the 26 stages (stage 27 on repeats stages 23..26).', '']
# arc_stage[stage][1 + k] is the parameter p<k> (game.c arc_frame)
for k, what in ((0, 'the row of the bomb table'), (1, 'the row of the boss sortie reload'), (2, 'the row of the butterfly sortie reload'),
                (3, 'the row of the bee sortie reload'), (4, 'the most divers and bombers at once'),
                (5, 'the same when the stage is older than 60 counts of tmr2'), (7, 'bombs without a pause when fewer aliens are left')):
    out += lines(f'arc_p{k}', f'p{k}: {what}', [row[1 + k] for row in stage])
out += lines('arc_beamstep', 'ticks of one of the 4 beam steps: p6 * 10 * 5 / 6 / 4 (p6 = 12, 9, 6 or 3)', [row[1 + 6] * 10 * 5 // 6 // 4 for row in stage])
out += lines('arc_bomb_tab', 'bomb flags (rows of 4) and boss sortie reloads (from 32)', nums(block('arc_bomb_tab')))
out += lines('arc_red_reload', 'sortie timer reloads of the butterflies (3 for each row)', nums(block('arc_red_reload')))
out += lines('arc_bee_reload', 'sortie timer reloads of the bees (3 for each row)', nums(block('arc_bee_reload')))
open(os.path.join(ROOT, 'src', 'arcade_data.asm'), 'w').write('\n'.join(out))
