/* Writes Galaga/paths_data.py: the flight paths, built by psp/game.c (floats there, integers here). */
#include <stdio.h>
#include "../../psp/game.c"

int main(void) {
    int p, k;
    paths_init();
    printf("# Generated by tools/gen_paths.py from psp/game.c: do not edit.\n");
    printf("# One entry per path A, B, C, D: (start x, start y, steps, per-step dx, per-step dy)\n");
    printf("PATHS = (\n");
    for (p = 0; p < 4; ++p) {
        printf("    (%d, %d, %d,\n     (", paths[p].sx, paths[p].sy, paths[p].n);
        for (k = 0; k < paths[p].n; ++k) printf("%d,%s", paths[p].dx[k], k % 24 == 23 ? "\n      " : "");
        printf("),\n     (");
        for (k = 0; k < paths[p].n; ++k) printf("%d,%s", paths[p].dy[k], k % 24 == 23 ? "\n      " : "");
        printf(")),\n");
    }
    printf(")\n");
    return 0;
}
