#!/usr/bin/env python3
"""Generate Galaga/arcade_data.py from ../psp/arcade_data.h (the numbers of the arcade rules, see ../ARCADE.md).
The header is read as numbers only. Path steps become base64 bytes (+128), so MicroPython keeps them as one byte each.
Usage: python3 tools/gen_arcade_data.py"""
import base64
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
src = open(os.path.join(ROOT, '..', 'psp', 'arcade_data.h')).read()


def nums(s):
    return [int(x) for x in re.findall(r'-?\d+', s)]


arrays = {m.group(1): nums(m.group(2)) for m in re.finditer(
    r'static const (?:signed char|short|unsigned char) (arc_\w+)(?:\[[^\]]*\])+ = \{(.*?)\};', src, re.S)}


def table(name, begin):
    """The rows of a struct table: each is '{numbers, arc_xx}' (the last item names an array)."""
    body = re.search(r'arc_%s\[[^\]]*\] = \{\n(.*?)\n\};' % name, src, re.S).group(1)
    return [(nums(m.group(1)), m.group(2)) for m in re.finditer(r'\{([^{}]*?),\s*(arc_\w+)\}', body)]


def blob(a):
    assert all(-128 <= v <= 127 for v in a)
    return base64.b64encode(bytes(v + 128 for v in a)).decode()


def rows(name, n):
    return [arrays[name][i:i + n] for i in range(0, len(arrays[name]), n)]


out = ['# Generated by tools/gen_arcade_data.py from psp/arcade_data.h: do not edit.',
       '# Numbers of the arcade Galaga (rank 3) from tomcoolpxl/cool8-cpu (MIT), a Python model of the arcade program made from the',
       '# disassembly hackbar/galaga. Flight paths, formation slots, wave lists, attack tables. See ARCADE.md. No pictures, no sounds.',
       'from binascii import a2b_base64', '']
paths = table('path', 0)
out.append('# (start x, start y, steps, frames to the first bomb, steps as bytes: dx + 128, dy + 128 for each step)')
out.append('ARC_PATH = (')
for (sx, sy, n, bt), name in paths:
    assert len(arrays[name]) == 2 * n
    out.append("    (%d, %d, %d, %d, a2b_base64('%s'))," % (sx, sy, n, bt, blob(arrays[name])))
out += [')', '']
out.append('ARC_NSTAGE = %d' % len(rows('arc_stage', 12)))
out.append('ARC_SLOT = (%s)' % ', '.join('(%d, %d)' % tuple(r) for r in rows('arc_slot', 2)))
out.append('# for each stage row: (challenge, hdr0 frames between two bombs, hdr1 bomb flags, launches: tick, slot (-1 = extra enemy), path ...)')
out.append('ARC_ROW = (')
body = re.search(r'arc_row\[[^\]]*\] = \{\n(.*?)\n\};', src, re.S).group(1)
for m in re.finditer(r'\{(\d+), (\d+), (arc_\w+), (\d+), (\d+)\}', body):
    ch, n, name, hdr0, hdr1 = int(m.group(1)), int(m.group(2)), m.group(3), int(m.group(4)), int(m.group(5))
    assert len(arrays[name]) == 3 * n
    out.append('    (%d, %d, %d, (%s)),' % (ch, hdr0, hdr1, ','.join(str(v) for v in arrays[name])))
out += [')', '']
out.append('# for each stage: row, then the parameters p0..p10')
out.append('ARC_STAGE = (%s)' % ', '.join('(%s)' % ','.join(str(v) for v in r) for r in rows('arc_stage', 12)))
out.append('# dive paths: (steps, frames of the whole dive, steps as bytes)')
out.append('ARC_DIVE_PATH = (')
for (n, total), name in table('dive_path', 0):
    assert len(arrays[name]) == 2 * n
    out.append("    (%d, %d, a2b_base64('%s'))," % (n, total, blob(arrays[name])))
out += [')', '']
d = arrays['arc_dive']
out.append('# ARC_DIVE[label][row][side]: index in ARC_DIVE_PATH or -1')
out.append('ARC_DIVE = (%s)' % ', '.join('(%s)' % ', '.join('(%d, %d)' % (d[(l * 5 + r) * 2], d[(l * 5 + r) * 2 + 1]) for r in range(5))
                                         for l in range(3)))
for name in ('slot_row', 'slot_side', 'entry_bomb', 'wingmen', 'slot_col', 'red_reload', 'bee_reload', 'bomb_tab'):
    out.append('ARC_%s = (%s)' % (name.upper(), ','.join(str(v) for v in arrays['arc_' + name])))
out.append('ARC_BREATH = (%s)' % ', '.join('(%s)' % ','.join(str(v) for v in r) for r in rows('arc_breath', 10)))
open(os.path.join(ROOT, 'Galaga', 'arcade_data.py'), 'w').write('\n'.join(out) + '\n')
print('Galaga/arcade_data.py', sum(len(x) + 1 for x in out), 'bytes')
