#!/usr/bin/env python3
"""Make src/game/arcade_data.s from ../psp/arcade_data.h: the numbers of the arcade rules for the Lynx (the 40 formation slots now; the
rest of the tables follow with the rules). The numbers come from tomcoolpxl/cool8-cpu (MIT), a model of the arcade program, through
tools/gen_arcade.py of the repository (see ../ARCADE.md). Usage: python3 tools/gen_arcade.py"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
H = open(os.path.join(ROOT, '..', 'psp', 'arcade_data.h')).read()


def block(name):
    return re.search(r'\b' + name + r'(?:\[[^\]]*\])+\s*=\s*\{(.*?)\n?\};', H, re.S).group(1)


def nums(text):
    return [int(v) for v in re.findall(r'-?\d+', text)]


slots = [nums(l) for l in block('arc_slot').strip().split('\n')]
assert len(slots) == 40
KIND = ['SPR_BOSS'] * 4 + ['SPR_BFLY'] * 16 + ['SPR_BEE'] * 20


def table(name, comment, items):
    out = [f'{name}: ; {comment}']
    for i in range(0, len(items), 8):
        out.append('    .byte ' + ','.join(str(v) for v in items[i:i + 8]))
    return out


out = ['; Generated by tools/gen_arcade.py from ../psp/arcade_data.h: do not edit. Numbers of the arcade Galaga from tomcoolpxl/cool8-cpu',
       '; (MIT), a model of the arcade program (see ../ARCADE.md).', '']
out += table('base_x', 'formation slot X low byte (left edge): 4 bosses, 16 butterflies, 20 bees', [s[0] & 255 for s in slots])
out += [''] + table('base_xh', 'formation slot X bit 8', [s[0] >> 8 for s in slots])
out += [''] + table('base_y', 'formation slot Y', [s[1] for s in slots])
out += ['', 'enemy_type_tbl: ; 0=boss 1=butterfly 2=bee', '    .byte ' + ','.join(['0'] * 4), '    .byte ' + ','.join(['1'] * 16),
        '    .byte ' + ','.join(['2'] * 20)]
out += ['', 'enemy_ptr_tbl: ; sprite id, frame A']
for i in range(0, 40, 8):
    out.append('    .byte ' + ','.join(KIND[i:i + 8]))
open(os.path.join(ROOT, 'src', 'game', 'arcade_data.s'), 'w').write('\n'.join(out) + '\n')
print('src/game/arcade_data.s')
