#!/usr/bin/env python3
"""Generate src/title.s: the title picture (160 x 89 pixels, 4 bpp, one Suzy literal sprite) and its palette.

The picture is assets/title-source.png (the C64 title picture), cropped to its content, scaled down and
reduced to 16 colours (fitted without the dim stars). Pens 0, 1 and 2 are black, white and red (the font pens): the nearest colours of the
picture become exactly those.
--portrait: src/portrait/title.s for the portrait ROM: the picture is 102 x 57 and turned for the screen (screen X = 56 - y, screen Y = x: see
tools/gen_art_portrait.py), so the sprite is 57 wide and 102 lines high.
Usage: python3 tools/gen_title.py [--portrait] [preview.png]
"""
import os
import sys
from PIL import Image, ImageEnhance

PORTRAIT = '--portrait' in sys.argv
if PORTRAIT:
    sys.argv.remove('--portrait')
W, H = (102, 57) if PORTRAIT else (160, 89)
src = Image.open('assets/title-source.png').convert('RGB').crop((0, 10, 1448, 815))
src = ImageEnhance.Color(src.resize((W, H), Image.LANCZOS)).enhance(2.0)   # keeps the green and blue aliens apart
# The palette is fitted to the picture without its dim star specks (they would take palette entries from the small
# aliens and the ship); every pixel, the specks too, then gets its nearest palette colour.
bright = Image.new('RGB', src.size)
bright.putdata([p if max(p) >= 120 else (0, 0, 0) for p in (src.get_flattened_data() if hasattr(src, 'get_flattened_data') else src.getdata())])
fit = bright.quantize(16, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
q = src.quantize(palette=fit, dither=Image.Dither.NONE)
pal = [tuple(fit.getpalette()[i * 3:i * 3 + 3]) for i in range(16)]


def nearest(c):
    return min(range(16), key=lambda i: sum((a - b) ** 2 for a, b in zip(pal[i], c)))


# Pens 0, 1 and 2 must be black, white and red (the font): the nearest picture colours become exactly those.
order = []
for want in ((0, 0, 0), (255, 255, 255), (238, 34, 0)):
    i = min((i for i in range(16) if i not in order), key=lambda i: sum((a - b) ** 2 for a, b in zip(pal[i], want)))
    order.append(i)
order += [i for i in range(16) if i not in order]
colours = [pal[i] for i in order]
colours[0], colours[1], colours[2] = (0, 0, 0), (255, 255, 255), (238, 34, 0)
pen = {old: new for new, old in enumerate(order)}
px = [pen[v] for v in q.get_flattened_data()] if hasattr(q, 'get_flattened_data') else [pen[v] for v in q.getdata()]

rows = [px[y * W:(y + 1) * W] for y in range(H)]
if PORTRAIT:                                      # turned: the screen line Y is the upright column x, the pixel X is H - 1 - y
    rows = [[rows[H - 1 - x][y] for x in range(H)] for y in range(W)]
lines = ['; Generated by tools/gen_title.py: do not edit.', '        .export title_pic, title_pal_g, title_pal_br', '',
         '        .segment "RODATA"', 'title_pic:']
for r in rows:
    row = r + [0, 0] if len(r) % 2 == 0 else r + [0, 0, 0]          # + padding: the last pixel of a line is lost
    data = ', '.join('$%02x' % (row[i] << 4 | row[i + 1]) for i in range(0, len(row), 2))
    lines.append(f'    .byte {len(row) // 2 + 1}, {data}')
lines.append('    .byte 0')
lines.append('title_pal_g:  .byte ' + ', '.join('$%x' % (c[1] >> 4) for c in colours))
lines.append('title_pal_br: .byte ' + ', '.join('$%02x' % ((c[2] >> 4) << 4 | c[0] >> 4) for c in colours))
path = 'src/portrait/title.s' if PORTRAIT else 'src/title.s'
os.makedirs(os.path.dirname(path), exist_ok=True)
open(path, 'w').write('\n'.join(lines) + '\n')
print(path, len(lines), 'lines')
if len(sys.argv) > 1:
    out = Image.new('RGB', (W, H))
    out.putdata([colours[p] for p in px])
    out.resize((W * 5, H * 5), Image.NEAREST).save(sys.argv[1])
