#!/usr/bin/env python3
"""Make src/game/arcade_data.s from ../psp/arcade_data.h: the numbers of the arcade rules for the Lynx. They come from
tomcoolpxl/cool8-cpu (MIT), a model of the arcade program, through tools/gen_arcade.py of the repository (see ../ARCADE.md).
The flight paths are packed: one byte for each step, an index in a table of the (dx, dy) pairs that occur.
Usage: python3 tools/gen_arcade.py"""
import os
import sys
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
PORTRAIT = 'portrait' in sys.argv[1:]            # the portrait field: ../psp/arcade_data_portrait.h -> src/game/arcade_data_portrait.s
H = open(os.path.join(ROOT, '..', 'psp', 'arcade_data_portrait.h' if PORTRAIT else 'arcade_data.h')).read()


def block(name):
    return re.search(r'\b' + name + r'(?:\[[^\]]*\])*\s*=\s*\{(.*?)\n?\};', H, re.S).group(1)


def nums(text):
    return [int(v) for v in re.findall(r'-?\d+', text)]


def rows(name):
    return [nums(l) for l in block(name).strip().split('\n')]


def arr(prefix, n):
    return [nums(re.search(r'\b%s%d\[\](?:\[3\])?\s*=\s*\{(.*?)\};' % (prefix, i), H, re.S).group(1)) for i in range(n)]


slots = rows('arc_slot')
slot_col = nums(block('arc_slot_col'))
slot_row = nums(block('arc_slot_row'))
slot_side = nums(block('arc_slot_side'))
entry_bomb = nums(block('arc_entry_bomb'))
wingmen = nums(block('arc_wingmen'))
stage = rows('arc_stage')
breath = rows('arc_breath')
paths_meta = [nums(l)[:4] for l in block('arc_path').strip().split('\n')]        # sx, sy, n, bt
paths = arr('arc_p', len(paths_meta))
dmeta = [nums(l)[:2] for l in block('arc_dive_path').strip().split('\n')]        # n, total
dives = arr('arc_d', len(dmeta))
dive_map = nums(block('arc_dive'))                                               # [3][5][2]
rowmeta = [re.findall(r'-?\d+', l) for l in block('arc_row').strip().split('\n')]
rowmeta = [[int(rm[0]), int(rm[1]), int(rm[3]), int(rm[4])] for rm in rowmeta]    # challenge, n, hdr0, hdr1
waves = arr('arc_w', len(rowmeta))                                                # flat: tick, slot, path
red_reload, bee_reload, bomb_tab = nums(block('arc_red_reload')), nums(block('arc_bee_reload')), nums(block('arc_bomb_tab'))
assert len(slots) == 40


def b(v):
    return v & 255


def lines(name, comment, items, per=16):
    out = [f'{name}: ; {comment}']
    for i in range(0, len(items), per):
        out.append('    .byte ' + ','.join(str(b(v)) if isinstance(v, int) else v for v in items[i:i + per]))
    return out + ['']


# ---- the paths as a bit stream: for each step the change of dx, then the change of dy against the step before
# (0 = '0', +1 = '10', -1 = '110', +2 = '1110', -2 = '11110', else '11111' and 9 bits of value + 256, low bit first); every path
# starts at a byte; bits are read from the low bit of a byte.
CODE = {0: '0', 1: '10', -1: '110', 2: '1110', -2: '11110'}


def encode(p):
    bits, px, py = '', 0, 0
    for k in range(0, len(p), 2):
        for cur, prev in ((p[k], px), (p[k + 1], py)):
            d = cur - prev
            bits += CODE.get(d) or '11111' + ''.join(str((d + 256) >> i & 1) for i in range(9))
        px, py = p[k], p[k + 1]
    bits += '0' * (-len(bits) % 8)
    return [int(bits[i:i + 8][::-1], 2) for i in range(0, len(bits), 8)]


def decode(data, n):                                  # what the 6502 does: it must give the path back
    pos, px, py, out = 0, 0, 0, []

    def bit():
        nonlocal pos
        v = data[pos >> 3] >> (pos & 7) & 1
        pos += 1
        return v

    def val():
        for i, v in enumerate((0, 1, -1, 2, -2)):
            if not bit():
                return v
        return sum(bit() << i for i in range(9)) - 256
    for _ in range(n):
        px += val()
        py += val()
        out += [px, py]
    return out


stream, starts = [], {}
for name, plist in (('arce', paths), ('arcd', dives)):
    for i, p in enumerate(plist):
        data = encode(p)
        assert decode(data, len(p) // 2) == p, (name, i)
        starts[(name, i)] = len(stream)
        stream += data

out = ['; Generated by tools/gen_arcade.py from ../psp/arcade_data.h: do not edit. Numbers of the arcade Galaga from tomcoolpxl/cool8-cpu',
       '; (MIT), a model of the arcade program (see ../ARCADE.md).', '']
out += lines('base_x', 'formation slot X low byte (left edge): 4 bosses, 16 butterflies, 20 bees', [s[0] & 255 for s in slots], 8)
out += lines('base_xh', 'formation slot X bit 8', [s[0] >> 8 for s in slots], 8)
out += lines('base_y', 'formation slot Y', [s[1] for s in slots], 8)
out += ['enemy_type_tbl: ; 0=boss 1=butterfly 2=bee', '    .byte ' + ','.join(['0'] * 4), '    .byte ' + ','.join(['1'] * 16),
        '    .byte ' + ','.join(['2'] * 20), '']
kinds = ['SPR_BOSS'] * 4 + ['SPR_BFLY'] * 16 + ['SPR_BEE'] * 20
out += lines('enemy_ptr_tbl', 'sprite id, frame A', kinds, 8)
out += lines('arc_slot_col', 'the column of a slot (0..9) for the breathing', slot_col, 20)
out += lines('arc_slot_row', 'the row of a slot: 0 boss, 1 and 2 butterfly, 3 and 4 bee', slot_row, 20)
out += lines('arc_slot_side', 'the side of a slot: 0 left, 1 right', slot_side, 20)
out += lines('arc_entry_bomb', 'the slots that may drop bombs while they fly in', entry_bomb, 20)
out += lines('arc_wingmen', 'the six butterflies that escort a boss, in the order of the arcade table', wingmen, 6)
for k in range(12):                       # one array for each column, so that a stage index (0..25) is an 8-bit offset
    out += lines('arc_st%d' % k, 'stage table column %d: %s' % (k, 'the row of waves' if k == 0 else 'parameter p%d' % (k - 1)), [r[k] for r in stage], 26)
out += lines('arc_fdx', 'the shift of the formation (in game units) for a swing position -32..32: %s, rounded towards zero' % ('pos * 88 / 100' if PORTRAIT else 'pos + pos * 3 / 7'),
             [(lambda q: int(q * 88 / 100) if PORTRAIT else q + int(q * 3 / 7))(q) for q in range(-32, 33)], 13)
out += lines('arc_red_reload', 'sortie timer reloads of the butterflies', red_reload, 15)
out += lines('arc_bee_reload', 'sortie timer reloads of the bees', bee_reload, 15)
out += lines('arc_bomb_tab', 'bomb flags and boss sortie timer reloads', bomb_tab, 16)
for k in range(10):
    out += lines('arc_br%d' % k, 'formation breathing, step 0..63: %s' % (('column %d' % k) if k < 5 else ('row %d' % (k - 5))), [r[k] for r in breath], 16)
# ---- rows of waves
out += lines('arc_row_chal', 'a row of waves is a challenge stage', [r[0] for r in rowmeta], 18)
out += lines('arc_row_n', 'the number of launches of a row', [r[1] for r in rowmeta], 18)
out += lines('arc_row_hdr0', 'ticks between two bombs of a flyer (255: none)', [r[2] for r in rowmeta], 18)
out += lines('arc_row_hdr1', 'the bomb flags of an alien that may bomb while it flies in', [r[3] for r in rowmeta], 18)
out += ['arc_row_lo:', '    .byte ' + ','.join(f'<arc_w{i}' for i in range(len(rowmeta))), 'arc_row_hi:',
        '    .byte ' + ','.join(f'>arc_w{i}' for i in range(len(rowmeta))), '']
for i, w in enumerate(waves):
    items = []
    prev = 0
    for k in range(0, len(w), 3):
        d = w[k] - prev
        assert 0 <= d < 65536, d
        items += [d & 255, d >> 8, w[k + 1] if w[k + 1] >= 0 else 255, w[k + 2]]
        prev = w[k]
    out += lines(f'arc_w{i}', 'launches: ticks since the last launch (16 bits), slot (255: none), path', items, 16)
# ---- paths
out += ['arc_stream: ; the flight paths as a bit stream']
for i in range(0, len(stream), 24):
    out.append('    .byte ' + ','.join(str(v) for v in stream[i:i + 24]))
out += ['']
for name, plist, meta in (('arce', paths, paths_meta), ('arcd', dives, dmeta)):
    out += ['%s_lo:' % name, '    .byte ' + ','.join(f'<(arc_stream+{starts[(name, i)]})' for i in range(len(plist))),
            '%s_hi:' % name, '    .byte ' + ','.join(f'>(arc_stream+{starts[(name, i)]})' for i in range(len(plist))), '']
    out += lines(f'{name}_nlo', 'steps', [len(p) // 2 & 255 for p in plist], 16)
    out += lines(f'{name}_nhi', '', [len(p) // 2 >> 8 for p in plist], 16)
out += lines('arce_sxlo', 'entry paths: start x, y (signed 16 bits), frames to the first bomb', [m[0] & 255 for m in paths_meta], 16)
out += lines('arce_sxhi', '', [m[0] >> 8 & 255 for m in paths_meta], 16)
out += lines('arce_sylo', '', [m[1] & 255 for m in paths_meta], 16)
out += lines('arce_syhi', '', [m[1] >> 8 & 255 for m in paths_meta], 16)
out += lines('arce_bt', '', [m[3] for m in paths_meta], 16)
out += lines('arcd_totlo', 'dive paths: ticks of the whole dive', [m[1] & 255 for m in dmeta], 16)
out += lines('arcd_tothi', '', [m[1] >> 8 for m in dmeta], 16)
out += lines('arc_dive_map', 'the dive path of [label 0 bee, 1 butterfly, 2 boss and wingmen][row 0..4][side]: 255 none', [v if v >= 0 else 255 for v in dive_map], 10)
size = sum(l.count(',') + 1 for l in out if l.startswith('    .byte'))
OUT = 'arcade_data_portrait.s' if PORTRAIT else 'arcade_data.s'
open(os.path.join(ROOT, 'src', 'game', OUT), 'w').write('\n'.join(out) + '\n')
print('src/game/' + OUT + ': about %d bytes (paths %d), %d entry paths, %d dive paths' % (size, len(stream), len(paths), len(dives)))
