#!/usr/bin/env python3
"""Generate src/font.s: the 3x5 HUD font as Suzy literal sprites (4 bpp, 4 px wide, 16 bytes per glyph).

Two copies, pen 1 (white) and pen 2 (red). Index = ASCII - 32, ' '..'Z'. Usage: python3 tools/gen_art.py
"""
G = {
    '0': '111101101101111', '1': '010110010010111', '2': '111001111100111', '3': '111001111001111',
    '4': '101101111001001', '5': '111100111001111', '6': '111100111101111', '7': '111001010010010',
    '8': '111101111101111', '9': '111101111001111',
    'A': '111101111101101', 'B': '110101110101110', 'C': '111100100100111', 'D': '110101101101110',
    'E': '111100110100111', 'F': '111100110100100', 'G': '111100101101111', 'H': '101101111101101',
    'I': '111010010010111', 'J': '001001001101111', 'K': '101101110101101', 'L': '100100100100111',
    'M': '101111111101101', 'N': '111101101101101', 'O': '010101101101010', 'P': '111101111100100',
    'Q': '111101101111001', 'R': '110101110101101', 'S': '011100010001110', 'T': '111010010010010',
    'U': '101101101101111', 'V': '101101101101010', 'W': '101101111111101', 'X': '101101010101101',
    'Y': '101101010010010', 'Z': '111001010100111', '-': '000000111000000', '!': '010010010000010',
    ':': '000010000010000',
}


def glyph(ch, pen):
    bits = G.get(ch, '0' * 15)
    out = []
    for r in range(5):
        row = bits[r * 3:r * 3 + 3] + '0'                   # 3 pixels + 1 blank column
        n = [pen if b == '1' else 0 for b in row]
        out.append(f'    .byte 3, ${n[0] << 4 | n[1]:02x}, ${n[2] << 4 | n[3]:02x}')
    out.append('    .byte 0')
    return out


lines = ['; Generated by tools/gen_art.py: do not edit.', '        .export font_w, font_r', '', '        .segment "RODATA"']
for name, pen in (('font_w', 1), ('font_r', 2)):
    lines.append(f'{name}:')
    for c in range(32, 91):
        lines.append(f'    ; {chr(c)}')
        lines += glyph(chr(c), pen)
open('src/font.s', 'w').write('\n'.join(lines) + '\n')
print('src/font.s')
