#!/usr/bin/env python3
"""Make src/paths_table.h from thumby/Galaga/paths_data.py (which thumby/tools/gen_paths.py builds from psp/game.c).
The Amiga build of psp/game.c (-DGAME_PATHS_TABLE) has no floating point: it reads the flight paths from this table, and
the formation slots too (a 68000 divides slowly).
Usage: python3 tools/gen_paths.py"""
import os
import sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, os.path.join(root, '..', 'thumby', 'Galaga'))
from paths_data import PATHS  # noqa: E402

out = ['/* Generated by amiga/tools/gen_paths.py: do not edit. Included by psp/game.c (-DGAME_PATHS_TABLE). */',
       'static Path paths[4] = {']
for sx, sy, n, dx, dy in PATHS:
    assert len(dx) == len(dy) == n <= 256
    out.append('    {%d, %d, %d,\n     {%s},\n     {%s}},' % (sx, sy, n, ','.join(map(str, dx)), ','.join(map(str, dy))))
out += ['};', 'static void paths_init(void) {}']
BOSS_X = (145, 171, 197, 223)                                     # the formation slots of psp/game.c (slot_x, slot_y), without the divisions
slots = [(BOSS_X[i] if i < 4 else 106 + 26 * ((i - 4) % 7), 72 if i < 4 else 100 + 28 * ((i - 4) // 7)) for i in range(32)]
out += ['static const short slot_xy[32][2] = {' + ', '.join('{%d, %d}' % s for s in slots) + '};', '']
open(os.path.join(root, 'src', 'paths_table.h'), 'w').write('\n'.join(out))
print('src/paths_table.h')
