; Generated by tools/gen_art.py: do not edit.
        .export font_w, font_r

        .segment "RODATA"
font_w:
    ;  
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; !
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $00, $00
    .byte 3, $01, $00
    .byte 0
    ; "
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; #
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; $
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; %
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; &
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; '
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; (
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; )
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; *
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; +
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; ,
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; -
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $11, $10
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; .
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; /
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; 0
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 0
    ; 1
    .byte 3, $01, $00
    .byte 3, $11, $00
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $11, $10
    .byte 0
    ; 2
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 3, $11, $10
    .byte 3, $10, $00
    .byte 3, $11, $10
    .byte 0
    ; 3
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 3, $11, $10
    .byte 0
    ; 4
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 3, $00, $10
    .byte 0
    ; 5
    .byte 3, $11, $10
    .byte 3, $10, $00
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 3, $11, $10
    .byte 0
    ; 6
    .byte 3, $11, $10
    .byte 3, $10, $00
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 0
    ; 7
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 0
    ; 8
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 0
    ; 9
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 3, $11, $10
    .byte 0
    ; :
    .byte 3, $00, $00
    .byte 3, $01, $00
    .byte 3, $00, $00
    .byte 3, $01, $00
    .byte 3, $00, $00
    .byte 0
    ; ;
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; <
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; =
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; >
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; ?
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; @
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; A
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 0
    ; B
    .byte 3, $11, $00
    .byte 3, $10, $10
    .byte 3, $11, $00
    .byte 3, $10, $10
    .byte 3, $11, $00
    .byte 0
    ; C
    .byte 3, $11, $10
    .byte 3, $10, $00
    .byte 3, $10, $00
    .byte 3, $10, $00
    .byte 3, $11, $10
    .byte 0
    ; D
    .byte 3, $11, $00
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $00
    .byte 0
    ; E
    .byte 3, $11, $10
    .byte 3, $10, $00
    .byte 3, $11, $00
    .byte 3, $10, $00
    .byte 3, $11, $10
    .byte 0
    ; F
    .byte 3, $11, $10
    .byte 3, $10, $00
    .byte 3, $11, $00
    .byte 3, $10, $00
    .byte 3, $10, $00
    .byte 0
    ; G
    .byte 3, $11, $10
    .byte 3, $10, $00
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 0
    ; H
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 0
    ; I
    .byte 3, $11, $10
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $11, $10
    .byte 0
    ; J
    .byte 3, $00, $10
    .byte 3, $00, $10
    .byte 3, $00, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 0
    ; K
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $00
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 0
    ; L
    .byte 3, $10, $00
    .byte 3, $10, $00
    .byte 3, $10, $00
    .byte 3, $10, $00
    .byte 3, $11, $10
    .byte 0
    ; M
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 0
    ; N
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 0
    ; O
    .byte 3, $01, $00
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $01, $00
    .byte 0
    ; P
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $10, $00
    .byte 3, $10, $00
    .byte 0
    ; Q
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 0
    ; R
    .byte 3, $11, $00
    .byte 3, $10, $10
    .byte 3, $11, $00
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 0
    ; S
    .byte 3, $01, $10
    .byte 3, $10, $00
    .byte 3, $01, $00
    .byte 3, $00, $10
    .byte 3, $11, $00
    .byte 0
    ; T
    .byte 3, $11, $10
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 0
    ; U
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 0
    ; V
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $01, $00
    .byte 0
    ; W
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $11, $10
    .byte 3, $11, $10
    .byte 3, $10, $10
    .byte 0
    ; X
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $01, $00
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 0
    ; Y
    .byte 3, $10, $10
    .byte 3, $10, $10
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 3, $01, $00
    .byte 0
    ; Z
    .byte 3, $11, $10
    .byte 3, $00, $10
    .byte 3, $01, $00
    .byte 3, $10, $00
    .byte 3, $11, $10
    .byte 0
font_r:
    ;  
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; !
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $00, $00
    .byte 3, $02, $00
    .byte 0
    ; "
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; #
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; $
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; %
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; &
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; '
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; (
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; )
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; *
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; +
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; ,
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; -
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $22, $20
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; .
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; /
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; 0
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 0
    ; 1
    .byte 3, $02, $00
    .byte 3, $22, $00
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $22, $20
    .byte 0
    ; 2
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 3, $22, $20
    .byte 3, $20, $00
    .byte 3, $22, $20
    .byte 0
    ; 3
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 3, $22, $20
    .byte 0
    ; 4
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 3, $00, $20
    .byte 0
    ; 5
    .byte 3, $22, $20
    .byte 3, $20, $00
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 3, $22, $20
    .byte 0
    ; 6
    .byte 3, $22, $20
    .byte 3, $20, $00
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 0
    ; 7
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 0
    ; 8
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 0
    ; 9
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 3, $22, $20
    .byte 0
    ; :
    .byte 3, $00, $00
    .byte 3, $02, $00
    .byte 3, $00, $00
    .byte 3, $02, $00
    .byte 3, $00, $00
    .byte 0
    ; ;
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; <
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; =
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; >
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; ?
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; @
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 3, $00, $00
    .byte 0
    ; A
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 0
    ; B
    .byte 3, $22, $00
    .byte 3, $20, $20
    .byte 3, $22, $00
    .byte 3, $20, $20
    .byte 3, $22, $00
    .byte 0
    ; C
    .byte 3, $22, $20
    .byte 3, $20, $00
    .byte 3, $20, $00
    .byte 3, $20, $00
    .byte 3, $22, $20
    .byte 0
    ; D
    .byte 3, $22, $00
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $00
    .byte 0
    ; E
    .byte 3, $22, $20
    .byte 3, $20, $00
    .byte 3, $22, $00
    .byte 3, $20, $00
    .byte 3, $22, $20
    .byte 0
    ; F
    .byte 3, $22, $20
    .byte 3, $20, $00
    .byte 3, $22, $00
    .byte 3, $20, $00
    .byte 3, $20, $00
    .byte 0
    ; G
    .byte 3, $22, $20
    .byte 3, $20, $00
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 0
    ; H
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 0
    ; I
    .byte 3, $22, $20
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $22, $20
    .byte 0
    ; J
    .byte 3, $00, $20
    .byte 3, $00, $20
    .byte 3, $00, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 0
    ; K
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $00
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 0
    ; L
    .byte 3, $20, $00
    .byte 3, $20, $00
    .byte 3, $20, $00
    .byte 3, $20, $00
    .byte 3, $22, $20
    .byte 0
    ; M
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 0
    ; N
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 0
    ; O
    .byte 3, $02, $00
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $02, $00
    .byte 0
    ; P
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $20, $00
    .byte 3, $20, $00
    .byte 0
    ; Q
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 0
    ; R
    .byte 3, $22, $00
    .byte 3, $20, $20
    .byte 3, $22, $00
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 0
    ; S
    .byte 3, $02, $20
    .byte 3, $20, $00
    .byte 3, $02, $00
    .byte 3, $00, $20
    .byte 3, $22, $00
    .byte 0
    ; T
    .byte 3, $22, $20
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 0
    ; U
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 0
    ; V
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $02, $00
    .byte 0
    ; W
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $22, $20
    .byte 3, $22, $20
    .byte 3, $20, $20
    .byte 0
    ; X
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $02, $00
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 0
    ; Y
    .byte 3, $20, $20
    .byte 3, $20, $20
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 3, $02, $00
    .byte 0
    ; Z
    .byte 3, $22, $20
    .byte 3, $00, $20
    .byte 3, $02, $00
    .byte 3, $20, $00
    .byte 3, $22, $20
    .byte 0
