; Generated by tools/gen_arcade.py from ../psp/arcade_data.h: do not edit. Numbers of the arcade Galaga from tomcoolpxl/cool8-cpu
; (MIT), a model of the arcade program (see ../ARCADE.md).

base_x: ; formation slot X low byte (left edge): 4 bosses, 16 butterflies, 20 bees
    .byte 138,206,161,183,92,252,92,252
    .byte 115,229,115,229,138,206,138,206
    .byte 161,183,161,183,69,19,69,19
    .byte 92,252,92,252,115,229,115,229
    .byte 138,206,138,206,161,183,161,183

base_xh: ; formation slot X bit 8
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,1,0,1
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0

base_y: ; formation slot Y
    .byte 72,72,72,72,100,100,128,128
    .byte 100,100,128,128,100,100,128,128
    .byte 100,100,128,128,156,156,184,184
    .byte 156,156,184,184,156,156,184,184
    .byte 156,156,184,184,156,156,184,184

enemy_type_tbl: ; 0=boss 1=butterfly 2=bee
    .byte 0,0,0,0
    .byte 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
    .byte 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

enemy_ptr_tbl: ; sprite id, frame A
    .byte SPR_BOSS,SPR_BOSS,SPR_BOSS,SPR_BOSS,SPR_BFLY,SPR_BFLY,SPR_BFLY,SPR_BFLY
    .byte SPR_BFLY,SPR_BFLY,SPR_BFLY,SPR_BFLY,SPR_BFLY,SPR_BFLY,SPR_BFLY,SPR_BFLY
    .byte SPR_BFLY,SPR_BFLY,SPR_BFLY,SPR_BFLY,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE
    .byte SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE
    .byte SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE,SPR_BEE
