#!/usr/bin/env python3
"""Generate src/paths.asm: the flight paths of the challenge stages.

Each path is a Catmull-Rom spline through a few control points (C64 sprite
coordinates: x 24..320, y 50..250 is the visible area), sampled at constant
speed. The game steps an alien one (dx, dy) entry per frame; mirrored waves
negate dx. Usage: python3 tools/gen_paths.py [preview.png]
"""
import math
import sys

SPEED = 2.6          # pixels per frame

PATHS = {
    # swoop in from the top left, one loop, exit bottom right
    'A': [(60, 30), (60, 30), (120, 88), (196, 128), (232, 100), (200, 66),
          (158, 96), (176, 156), (236, 204), (290, 246), (290, 246)],
    # S-curve in from the top right, exit bottom right
    'B': [(292, 30), (292, 30), (236, 72), (120, 92), (62, 132), (98, 174),
          (206, 188), (274, 214), (296, 246), (296, 246)],
}


def catmull(pts, samples_per_seg=60):
    out = []
    for i in range(1, len(pts) - 2):
        p0, p1, p2, p3 = pts[i - 1], pts[i], pts[i + 1], pts[i + 2]
        for k in range(samples_per_seg):
            t = k / samples_per_seg
            t2, t3 = t * t, t * t * t
            out.append(tuple(
                0.5 * ((2 * p1[j]) + (-p0[j] + p2[j]) * t +
                       (2 * p0[j] - 5 * p1[j] + 4 * p2[j] - p3[j]) * t2 +
                       (-p0[j] + 3 * p1[j] - 3 * p2[j] + p3[j]) * t3)
                for j in range(2)))
    out.append(pts[-2])
    return out


def walk(curve, speed):
    """Constant-speed samples along the polyline, as integer positions."""
    pos = [curve[0]]
    carry = 0.0
    for a, b in zip(curve, curve[1:]):
        seg = math.dist(a, b)
        d = speed - carry
        while d <= seg:
            t = d / seg
            pos.append((a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t))
            d += speed
        carry = seg - (d - speed)
    return [(round(x), round(y)) for x, y in pos]


def main():
    asm = ["; Challenge stage flight paths. Generated by tools/gen_paths.py: do not edit.", ""]
    preview = []
    for name, pts in PATHS.items():
        pos = walk(catmull(pts), SPEED)
        steps = [(b[0] - a[0], b[1] - a[1]) for a, b in zip(pos, pos[1:])]
        assert len(steps) < 256 and all(abs(v) < 128 for s in steps for v in s)
        preview.append((name, pos))
        asm.append("PATH%s_X0    = %d" % (name, pos[0][0]))
        asm.append("PATH%s_Y0    = %d" % (name, pos[0][1]))
        asm.append("PATH%s_LEN   = %d" % (name, len(steps)))
        for axis, lab in ((0, 'dx'), (1, 'dy')):
            asm.append("path%s_%s:" % (name, lab))
            vals = [s[axis] & 255 for s in steps]
            for i in range(0, len(vals), 16):
                asm.append("    !byte " + ",".join("$%02x" % v for v in vals[i:i + 16]))
        asm.append("")
    open('src/paths.asm', 'w').write("\n".join(asm))
    print({n: len(p) - 1 for n, p in preview})
    if len(sys.argv) > 1:
        from PIL import Image, ImageDraw
        im = Image.new('RGB', (368 * 2, 256 * 2), 'black')
        d = ImageDraw.Draw(im)
        d.rectangle([24 * 2, 50 * 2, 344 * 2, 250 * 2], outline='#444')
        for (name, pos), col in zip(preview, ('#f66', '#6cf')):
            d.line([(x * 2, y * 2) for x, y in pos], fill=col, width=2)
            mir = [((344 - x) * 2, y * 2) for x, y in pos]
            d.line(mir, fill=col, width=1)
        im.save(sys.argv[1])


main()
