; The numbers of the arcade rules for the C64. Generated by tools/gen_arcade.py from ../psp/arcade_data.h: do not edit.
; One entry for each of the 26 stages (stage 27 on repeats stages 23..26).

arc_p0: ; p0: the row of the bomb table
    !byte 0,0,0,1,1,2,0,2,2,1,0,3,3,3,0,4
    !byte 4,1,0,5,5,5,0,6,6,6

arc_p1: ; p1: the row of the boss sortie reload
    !byte 0,0,0,1,1,1,0,2,2,0,0,2,2,2,0,2
    !byte 2,1,0,2,2,2,0,2,2,2

arc_p2: ; p2: the row of the butterfly sortie reload
    !byte 0,1,0,1,2,2,0,2,3,1,0,4,6,6,0,7
    !byte 7,2,0,8,8,8,0,8,9,9

arc_p3: ; p3: the row of the bee sortie reload
    !byte 0,1,0,2,3,4,0,5,6,1,0,6,7,7,0,8
    !byte 8,2,0,8,8,8,0,9,9,9

arc_p4: ; p4: the most divers and bombers at once
    !byte 2,2,0,2,2,3,0,3,3,2,0,3,4,4,0,4
    !byte 4,2,0,4,5,5,0,5,5,5

arc_p5: ; p5: the same when the stage is older than 60 counts of tmr2
    !byte 2,3,0,3,3,3,0,3,4,3,0,4,4,5,0,5
    !byte 5,3,0,6,6,6,0,7,7,7

arc_p7: ; p7: bombs without a pause when fewer aliens are left
    !byte 6,7,0,7,8,8,0,9,9,7,0,7,8,8,0,9
    !byte 9,7,0,10,10,12,0,12,12,12

arc_beamstep: ; ticks of one of the 4 beam steps: p6 * 10 * 5 / 6 / 4 (p6 = 12, 9, 6 or 3)
    !byte 25,25,25,18,18,18,18,18,12,18,12,12,12,12,12,12
    !byte 12,18,12,6,6,6,6,6,6,6

arc_bomb_tab: ; bomb flags (rows of 4) and boss sortie reloads (from 32)
    !byte 3,3,1,1,3,3,3,1,7,3,3,1,7,3,3,3
    !byte 7,7,3,3,15,7,3,3,15,7,7,3,15,7,7,7
    !byte 6,10,15,15,4,8,13,13,4,6,10,10,58

arc_red_reload: ; sortie timer reloads of the butterflies (3 for each row)
    !byte 9,7,5,8,6,4,7,5,4,6,4,3,5,3,3,4
    !byte 3,3,4,2,2,3,3,2,3,2,2,2,2,2

arc_bee_reload: ; sortie timer reloads of the bees (3 for each row)
    !byte 6,5,4,5,4,3,5,3,3,4,3,2,4,2,2,3
    !byte 3,2,3,2,1,2,2,1,2,1,1,1,1,1
