; Hi-score digit glyphs for the title picture (multicolor bitmap, colour %11), 8 bytes each.
; Generated by tools/gen_title.py: do not edit.
title_digits:
    !byte $fc,$cc,$cc,$cc,$cc,$cc,$fc,$00   ; 0
    !byte $30,$f0,$30,$30,$30,$30,$fc,$00   ; 1
    !byte $fc,$0c,$0c,$fc,$c0,$c0,$fc,$00   ; 2
    !byte $fc,$0c,$0c,$fc,$0c,$0c,$fc,$00   ; 3
    !byte $cc,$cc,$cc,$fc,$0c,$0c,$0c,$00   ; 4
    !byte $fc,$c0,$c0,$fc,$0c,$0c,$fc,$00   ; 5
    !byte $fc,$c0,$c0,$fc,$cc,$cc,$fc,$00   ; 6
    !byte $fc,$0c,$0c,$30,$30,$30,$30,$00   ; 7
    !byte $fc,$cc,$cc,$fc,$cc,$cc,$fc,$00   ; 8
    !byte $fc,$cc,$cc,$fc,$0c,$0c,$fc,$00   ; 9
