#!/usr/bin/env python3
"""Generate src/art.rs from ../psp/art.h: our own 16x16 pixel art (16 rows of 8 letters: the left half, mirrored by the renderer).
The letters are colours (see the header). Usage: python3 tools/gen_art_rs.py"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
src = open(os.path.join(ROOT, '..', 'psp', 'art.h')).read()
out = ['// Generated by tools/gen_art_rs.py from psp/art.h: do not edit. Our own art: 16 rows of 8 letters, the left half of a 16 x 16 picture.',
       '// . clear | m main, M light, n dark (per variant) | y yellow, Y dark yellow, c cyan, w white, k near-black, o orange, r red, b blue, g grey',
       '#![allow(dead_code)]', '']
for m in re.finditer(r'static ArtRows (art_\w+) = \{(.*?)\};', src, re.S):
    rows = re.findall(r'"([^"]*)"', m.group(2))
    assert len(rows) == 16 and all(len(r) == 8 for r in rows), m.group(1)
    out.append('pub static %s: [&str; 16] = [%s];' % (m.group(1).upper(), ', '.join('"%s"' % r for r in rows)))
open(os.path.join(ROOT, 'src', 'art.rs'), 'w').write('\n'.join(out) + '\n')
print('src/art.rs', len(out) - 4, 'pictures')
