#!/usr/bin/env python3
"""Generate src/arcade_data.rs from ../psp/arcade_data.h (the numbers of the arcade rules, see ../ARCADE.md).
The header is read as numbers only; the names are the names of the header in capitals.
Usage: python3 tools/gen_arcade_rs.py"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
src = open(os.path.join(ROOT, '..', 'psp', 'arcade_data.h')).read()


def nums(s):
    return [int(x) for x in re.findall(r'-?\d+', s)]


arrays = {m.group(1): nums(m.group(2)) for m in re.finditer(
    r'static const (?:signed char|short|unsigned char) (arc_\w+)(?:\[[^\]]*\])+ = \{(.*?)\};', src, re.S)}


def body(name):
    return re.search(r'arc_%s\[[^\]]*\] = \{\n(.*?)\n\};' % name, src, re.S).group(1)


def table(name):
    """The rows of a struct table: each is '{numbers, arc_xx}' (the last item names an array)."""
    return [(nums(m.group(1)), m.group(2)) for m in re.finditer(r'\{([^{}]*?),\s*(arc_\w+)\}', body(name))]


def rows(name, n):
    return [arrays[name][i:i + n] for i in range(0, len(arrays[name]), n)]


def lst(a):
    return ','.join(str(v) for v in a)


out = ['// Generated by tools/gen_arcade_rs.py from psp/arcade_data.h: do not edit.',
       '// Numbers of the arcade Galaga (rank 3) from tomcoolpxl/cool8-cpu (MIT), a Python model of the arcade program made from the',
       '// disassembly hackbar/galaga. Flight paths, formation slots, wave lists, attack tables. See ARCADE.md. No pictures, no sounds.',
       '#![allow(dead_code)]', '']
paths = table('path')
for i, ((sx, sy, n, bt), name) in enumerate(paths):
    assert len(arrays[name]) == 2 * n
    out.append('static P%d: [i8; %d] = [%s];' % (i, 2 * n, lst(arrays[name])))
out.append('/// start x, start y, steps, frames to the first bomb, the steps (dx, dy for each tick)')
out.append('pub struct Path { pub sx: i32, pub sy: i32, pub n: i32, pub bt: i32, pub d: &\'static [i8] }')
out.append('pub static ARC_PATH: [Path; %d] = [' % len(paths))
for i, ((sx, sy, n, bt), name) in enumerate(paths):
    out.append('    Path { sx: %d, sy: %d, n: %d, bt: %d, d: &P%d },' % (sx, sy, n, bt, i))
out += ['];', '']
nstage = len(rows('arc_stage', 12))
out.append('pub const ARC_NSTAGE: i32 = %d;' % nstage)
out.append('pub static ARC_SLOT: [[i32; 2]; 40] = [%s];' % ','.join('[%s]' % lst(r) for r in rows('arc_slot', 2)))
out.append('/// For a stage row: challenge, launches (tick, slot (-1 = extra enemy), path), hdr0 (frames between two bombs), hdr1 (bomb flags of an enemy that flies in)')
out.append('pub struct Row { pub challenge: bool, pub l: &\'static [[i32; 3]], pub hdr0: i32, pub hdr1: i32 }')
rowsl = list(re.finditer(r'\{(\d+), (\d+), (arc_\w+), (\d+), (\d+)\}', body('row')))
for i, m in enumerate(rowsl):
    n, name = int(m.group(2)), m.group(3)
    assert len(arrays[name]) == 3 * n
    out.append('static W%d: [[i32; 3]; %d] = [%s];' % (i, n, ','.join('[%s]' % lst(arrays[name][k:k + 3]) for k in range(0, 3 * n, 3))))
out.append('pub static ARC_ROW: [Row; %d] = [' % len(rowsl))
for i, m in enumerate(rowsl):
    out.append('    Row { challenge: %s, l: &W%d, hdr0: %s, hdr1: %s },' % ('true' if m.group(1) == '1' else 'false', i, m.group(4), m.group(5)))
out += ['];', '']
out.append('/// For each stage: the row, then the parameters p0..p10')
out.append('pub static ARC_STAGE: [[i32; 12]; %d] = [%s];' % (nstage, ','.join('[%s]' % lst(r) for r in rows('arc_stage', 12))))
dpaths = table('dive_path')
for i, ((n, total), name) in enumerate(dpaths):
    assert len(arrays[name]) == 2 * n
    out.append('static D%d: [i8; %d] = [%s];' % (i, 2 * n, lst(arrays[name])))
out.append('/// Dive paths: steps, ticks of the whole dive, the steps')
out.append('pub struct DivePath { pub n: i32, pub total: i32, pub d: &\'static [i8] }')
out.append('pub static ARC_DIVE_PATH: [DivePath; %d] = [' % len(dpaths))
for i, ((n, total), name) in enumerate(dpaths):
    out.append('    DivePath { n: %d, total: %d, d: &D%d },' % (n, total, i))
out += ['];', '']
d = arrays['arc_dive']
out.append('/// ARC_DIVE[label][row][side]: the index in ARC_DIVE_PATH, or -1')
out.append('pub static ARC_DIVE: [[[i32; 2]; 5]; 3] = [%s];' % ','.join(
    '[%s]' % ','.join('[%d,%d]' % (d[(l * 5 + r) * 2], d[(l * 5 + r) * 2 + 1]) for r in range(5)) for l in range(3)))
for name, ty in (('slot_row', 'i32'), ('slot_side', 'i32'), ('entry_bomb', 'i32'), ('wingmen', 'i32'), ('slot_col', 'i32'),
                 ('red_reload', 'i32'), ('bee_reload', 'i32'), ('bomb_tab', 'i32')):
    out.append('pub static ARC_%s: [%s; %d] = [%s];' % (name.upper(), ty, len(arrays['arc_' + name]), lst(arrays['arc_' + name])))
out.append('pub static ARC_BREATH: [[i32; 10]; %d] = [%s];' % (len(rows('arc_breath', 10)), ','.join('[%s]' % lst(r) for r in rows('arc_breath', 10))))
open(os.path.join(ROOT, 'src', 'arcade_data.rs'), 'w').write('\n'.join(out) + '\n')
print('src/arcade_data.rs', sum(len(x) + 1 for x in out), 'bytes')
