#!/usr/bin/env python3
"""assets/title-source.png -> logo.h: the GALAGA lettering as a 256x64 RGBA texture (black keyed out)."""
from PIL import Image
from collections import deque
im = Image.open('assets/title-source.png').convert('RGB')
crop = im.crop((0, 0, im.width, 300))
w, h = crop.size
px = crop.load()
lit = [[max(px[x, y]) > 40 for x in range(w)] for y in range(h)]
seen = [[False] * w for _ in range(h)]
keep = []
for y0 in range(h):
    for x0 in range(w):
        if lit[y0][x0] and not seen[y0][x0]:
            comp, q = [], deque([(x0, y0)])
            seen[y0][x0] = True
            while q:
                x, y = q.popleft(); comp.append((x, y))
                for nx, ny in ((x+1, y), (x-1, y), (x, y+1), (x, y-1)):
                    if 0 <= nx < w and 0 <= ny < h and lit[ny][nx] and not seen[ny][nx]:
                        seen[ny][nx] = True; q.append((nx, ny))
            if len(comp) > 3000: keep += comp   # letters; stars are tiny
rgba = Image.new('RGBA', (w, h), (0, 0, 0, 0))
o = rgba.load()
for x, y in keep: o[x, y] = px[x, y] + (255,)
logo = rgba.crop(rgba.getbbox()).resize((256, 0), Image.LANCZOS) if False else rgba.crop(rgba.getbbox())
lh = round(logo.height * 256 / logo.width)
logo = logo.resize((256, lh), Image.LANCZOS)
tex = Image.new('RGBA', (256, 64), (0, 0, 0, 0)); tex.paste(logo, (0, 0))
d = list(tex.getdata())
with open('logo.h', 'w') as f:
    f.write('/* generated by tools/logo2h.py */\n#define LOGO_W 256\n#define LOGO_H 64\n#define LOGO_DRAW_H %d\n' % lh)
    f.write('static const unsigned int logo_px[256 * 64] = {')
    for i, (r, g, b, a) in enumerate(d):
        f.write('%s0x%08x,' % ('\n' if i % 8 == 0 else '', a << 24 | b << 16 | g << 8 | r))
    f.write('\n};\n')
tex.save('/tmp/logo_preview.png') if False else None
print('logo', logo.size)
